"""Envirolytics companion backend.

Three responsibilities only:
  1. Relay push registration to the Emergent-managed push service.
  2. Run a background poller that queries monitor.envirolytics.in on behalf of
     each registered user and fires push notifications when a device goes
     offline or a limit breach is detected.
  3. Send report emails (on-demand + weekly + monthly) via SendGrid from
     info@envirolytics.in with CSV & PDF attachments generated by the
     upstream API.

The mobile app talks to monitor.envirolytics.in DIRECTLY for all data; this
backend never proxies user-facing reads. It only exists so push + email work.
"""
from __future__ import annotations

import asyncio
import base64
import logging
import os
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import httpx
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
from dotenv import load_dotenv
from fastapi import FastAPI, APIRouter, HTTPException
from motor.motor_asyncio import AsyncIOMotorClient
from pydantic import BaseModel, EmailStr, Field
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Attachment, Disposition, FileContent, FileName, FileType, Mail
from starlette.middleware.cors import CORSMiddleware

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / ".env")

MONGO_URL = os.environ["MONGO_URL"]
DB_NAME = os.environ["DB_NAME"]
EMERGENT_PUSH_KEY = os.environ.get("EMERGENT_PUSH_KEY", "placeholder")
ENVIROLYTICS_BASE_URL = os.environ.get(
    "ENVIROLYTICS_BASE_URL", "https://monitor.envirolytics.in"
)
ALERT_POLL_INTERVAL_SECONDS = int(
    os.environ.get("ALERT_POLL_INTERVAL_SECONDS", "300")
)
SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", "placeholder")
SENDER_EMAIL = os.environ.get("SENDER_EMAIL", "info@envirolytics.in")
SENDER_NAME = os.environ.get("SENDER_NAME", "Envirolytics Monitor")
REPORT_TIMEZONE = os.environ.get("REPORT_SCHEDULE_TIMEZONE", "Asia/Kolkata")
PUSH_BASE_URL = "https://integrations.emergentagent.com"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger("envirolytics")

_mongo = AsyncIOMotorClient(MONGO_URL)
db = _mongo[DB_NAME]

# One shared httpx client for the Emergent push relay.
_push_client = httpx.AsyncClient(
    base_url=PUSH_BASE_URL,
    headers={"X-Push-Key": EMERGENT_PUSH_KEY},
    timeout=10.0,
)
# One shared httpx client for the Envirolytics upstream API.
_envirolytics_client = httpx.AsyncClient(
    base_url=ENVIROLYTICS_BASE_URL, timeout=15.0
)


# ---------------------------------------------------------------------------
# Push relay
# ---------------------------------------------------------------------------


class RegisterPushBody(BaseModel):
    user_id: str
    platform: str  # "android" | "ios"
    device_token: str
    envirolytics_token: str | None = None  # so the poller can call the upstream
    email: EmailStr | None = None  # for scheduled reports
    full_name: str | None = None
    role: str | None = None


async def send_push(
    recipients: list[str],
    data: dict,
    idempotency_key: str | None = None,
) -> None:
    if not recipients:
        return
    if len(recipients) > 100:
        raise ValueError("max 100 recipients per /trigger call")
    if "title" not in data or "message" not in data:
        raise ValueError("data must include title and message")
    payload: dict[str, Any] = {"recipients": recipients, "data": data}
    if idempotency_key:
        payload["$idempotency_key"] = idempotency_key
    resp = await _push_client.post("/api/v1/push/trigger", json=payload)
    if resp.status_code == 401:
        raise HTTPException(500, "EMERGENT_PUSH_KEY missing or invalid")
    if resp.status_code >= 500:
        raise HTTPException(502, "Push provider unavailable")
    resp.raise_for_status()


# ---------------------------------------------------------------------------
# Alert poller
# ---------------------------------------------------------------------------


def _breach_signature(b: dict) -> str:
    """Stable key so we don't re-notify the same breach every poll."""
    return "|".join(
        str(b.get(k, "")) for k in ("hardware_id", "parameter", "detected_at", "value")
    )


async def _poll_user(user_doc: dict) -> None:
    token = user_doc.get("envirolytics_token")
    user_id = user_doc.get("user_id")
    if not token or not user_id:
        return
    headers = {"Authorization": f"Bearer {token}"}
    try:
        off_resp, breach_resp = await asyncio.gather(
            _envirolytics_client.get(
                "/api/alerts/offline?hours=24", headers=headers
            ),
            _envirolytics_client.get(
                "/api/alerts/limit-breaches", headers=headers
            ),
        )
    except Exception as exc:  # network hiccup — skip this cycle
        logger.warning("Envirolytics poll failed for %s: %s", user_id, exc)
        return

    if off_resp.status_code == 401 or breach_resp.status_code == 401:
        # Token expired — mark user token invalid so we stop polling.
        await db.push_users.update_one(
            {"user_id": user_id},
            {"$unset": {"envirolytics_token": ""}, "$set": {"token_invalid": True}},
        )
        logger.info("Envirolytics token expired for %s", user_id)
        return

    off_ids = {
        d.get("hardware_id")
        for d in (off_resp.json().get("offline") or [])
        if d.get("hardware_id")
    }
    prev_off = set(user_doc.get("known_offline") or [])
    new_offline = off_ids - prev_off

    breaches = breach_resp.json().get("breaches") or []
    breach_sigs = {_breach_signature(b) for b in breaches}
    prev_breaches = set(user_doc.get("known_breaches") or [])
    new_breach_sigs = breach_sigs - prev_breaches

    async def _notify(title: str, message: str, key: str) -> None:
        try:
            await send_push(
                recipients=[user_id],
                data={"title": title, "message": message, "action_url": "/(tabs)/alerts"},
                idempotency_key=key,
            )
        except Exception as exc:  # push failure never blocks the poller
            logger.warning("push send failed: %s", exc)

    for hw in new_offline:
        await _notify(
            "Device offline",
            f"{hw} has not reported in 24h.",
            key=f"offline:{user_id}:{hw}",
        )
    for b in breaches:
        sig = _breach_signature(b)
        if sig not in new_breach_sigs:
            continue
        await _notify(
            "Limit breach",
            f"{b.get('parameter','value')} on {b.get('hardware_id','device')} "
            f"= {b.get('value','?')} (limit {b.get('limit','?')}).",
            key=f"breach:{user_id}:{sig}",
        )

    await db.push_users.update_one(
        {"user_id": user_id},
        {
            "$set": {
                "known_offline": list(off_ids),
                "known_breaches": list(breach_sigs),
            }
        },
    )


async def _poller_loop() -> None:
    while True:
        try:
            cursor = db.push_users.find(
                {"envirolytics_token": {"$exists": True, "$ne": None}}
            )
            async for user in cursor:
                await _poll_user(user)
        except Exception as exc:
            logger.exception("Alert poller loop error: %s", exc)
        await asyncio.sleep(ALERT_POLL_INTERVAL_SECONDS)


# ---------------------------------------------------------------------------
# Email (SendGrid)
# ---------------------------------------------------------------------------

ATTACHMENT_KINDS: dict[str, tuple[str, str, str]] = {
    # kind -> (instrument_type, format, mime)
    "flowmeter_csv": ("flowmeter", "csv", "text/csv"),
    "flowmeter_pdf": ("flowmeter", "pdf", "application/pdf"),
    "dwlr_csv": ("dwlr", "csv", "text/csv"),
    "dwlr_pdf": ("dwlr", "pdf", "application/pdf"),
}


async def _fetch_attachment(
    token: str,
    instrument_type: str,
    fmt: str,
    hardware_id: str | None,
    days: int | None,
) -> tuple[bytes, str, str]:
    """Download a report from the Envirolytics API. Returns (bytes, mime, filename)."""
    params: dict[str, str] = {"instrument_type": instrument_type, "format": fmt}
    if hardware_id:
        params["hardware_id"] = hardware_id
    if days:
        params["days"] = str(days)
    resp = await _envirolytics_client.get(
        "/api/flowmeter-mgmt/export",
        params=params,
        headers={"Authorization": f"Bearer {token}"},
    )
    if resp.status_code == 401:
        raise HTTPException(401, "Envirolytics token invalid — please sign in again.")
    if resp.status_code >= 400:
        raise HTTPException(502, f"Upstream export failed ({resp.status_code}).")
    mime = "text/csv" if fmt == "csv" else "application/pdf"
    from datetime import datetime, timezone as _tz

    stamp = datetime.now(_tz.utc).strftime("%Y-%m-%d")
    filename = f"envirolytics_{instrument_type}_{stamp}.{fmt}"
    return resp.content, mime, filename


def _build_html(intro: str, cadence: str | None = None) -> str:
    """Simple branded HTML wrapper for the email body."""
    tag = f"{cadence.title()} report" if cadence else "Report"
    return f"""
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background:#f6f7f9; padding:24px;">
      <div style="max-width:560px; margin:0 auto; background:#ffffff; border-radius:12px; overflow:hidden; border:1px solid #e5e7eb;">
        <div style="background:#1a2332; padding:20px 24px; color:#f8fafc;">
          <div style="font-size:11px; letter-spacing:3px; color:#94a3b8; font-weight:700;">ENVIROLYTICS · MONITOR</div>
          <div style="font-size:20px; font-weight:800; margin-top:4px;">{tag}</div>
        </div>
        <div style="padding:24px; color:#111827; line-height:1.5; font-size:14px;">
          {intro}
          <p style="margin-top:24px; color:#6b7280; font-size:12px;">
            Attached files are generated directly by the Envirolytics platform (monitor.envirolytics.in). Open the CSV in Excel/Google Sheets or the PDF in any viewer.
          </p>
        </div>
        <div style="padding:16px 24px; background:#f9fafb; color:#9ca3af; font-size:11px; text-align:center; border-top:1px solid #e5e7eb;">
          Sent by Envirolytics Sustainability Pvt Ltd · info@envirolytics.in
        </div>
      </div>
    </div>
    """


async def send_report_email(
    to_email: str,
    envirolytics_token: str,
    kinds: list[str],
    subject: str,
    intro_html: str,
    cadence: str | None = None,
    hardware_id: str | None = None,
    days: int | None = None,
) -> None:
    """Fetch each requested kind of report and email as SendGrid attachments."""
    if SENDGRID_API_KEY in ("", "placeholder"):
        raise HTTPException(500, "SENDGRID_API_KEY not configured on the server.")
    unknown = [k for k in kinds if k not in ATTACHMENT_KINDS]
    if unknown:
        raise HTTPException(400, f"Unknown attachment kind(s): {unknown}")
    message = Mail(
        from_email=(SENDER_EMAIL, SENDER_NAME),
        to_emails=to_email,
        subject=subject,
        html_content=_build_html(intro_html, cadence),
    )
    for kind in kinds:
        instrument_type, fmt, _ = ATTACHMENT_KINDS[kind]
        content, mime, filename = await _fetch_attachment(
            envirolytics_token, instrument_type, fmt, hardware_id, days
        )
        att = Attachment()
        att.file_content = FileContent(base64.b64encode(content).decode())
        att.file_name = FileName(filename)
        att.file_type = FileType(mime)
        att.disposition = Disposition("attachment")
        message.add_attachment(att)

    def _send_sync() -> None:
        SendGridAPIClient(SENDGRID_API_KEY).send(message)

    try:
        # SendGrid client is sync; run in the default executor.
        await asyncio.to_thread(_send_sync)
    except Exception as exc:
        logger.exception("SendGrid failed: %s", exc)
        raise HTTPException(502, "Email provider failed to send the report.")


async def _send_scheduled_reports(cadence: str) -> None:
    """Called by APScheduler for `weekly` or `monthly` cadences."""
    if SENDGRID_API_KEY in ("", "placeholder"):
        logger.warning("Skipping scheduled reports — SENDGRID_API_KEY not set.")
        return
    days = 7 if cadence == "weekly" else 30
    query = {
        "envirolytics_token": {"$exists": True, "$ne": None},
        f"subscriptions.{cadence}": True,
    }
    async for user in db.push_users.find(query):
        email = user.get("email") or user.get("user_email")
        if not email:
            continue
        try:
            await send_report_email(
                to_email=email,
                envirolytics_token=user["envirolytics_token"],
                kinds=[
                    "flowmeter_csv",
                    "flowmeter_pdf",
                    "dwlr_csv",
                    "dwlr_pdf",
                ],
                subject=f"Envirolytics {cadence} report",
                intro_html=(
                    f"<p>Hi {user.get('full_name', 'there')},</p>"
                    f"<p>Attached is your {cadence} compliance report bundle covering the last <b>{days} days</b> of instrument activity.</p>"
                ),
                cadence=cadence,
                days=days,
            )
        except Exception as exc:  # never crash the scheduler on a single failure
            logger.warning("Scheduled email failed for %s: %s", email, exc)


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------


async def _auto_deactivate_expired_users() -> None:
    """Runs daily. For each registered admin user, ask the upstream for the
    subuser list and PUT is_active=false on anyone whose account is more than
    365 days old and still marked active.
    """
    from datetime import datetime, timezone as _tz

    admins = db.push_users.find(
        {
            "envirolytics_token": {"$exists": True, "$ne": None},
            "$or": [{"role": "admin"}, {"is_admin": True}],
        }
    )
    handled = 0
    async for adm in admins:
        token = adm.get("envirolytics_token")
        if not token:
            continue
        try:
            resp = await _envirolytics_client.get(
                "/api/admin/users/list",
                headers={"Authorization": f"Bearer {token}"},
            )
        except Exception as exc:
            logger.warning("auto-deactivate: list failed for %s: %s", adm.get("user_id"), exc)
            continue
        if resp.status_code == 401:
            await db.push_users.update_one(
                {"user_id": adm.get("user_id")},
                {"$unset": {"envirolytics_token": ""}, "$set": {"token_invalid": True}},
            )
            continue
        if resp.status_code >= 400:
            continue
        now = datetime.now(_tz.utc)
        for u in resp.json().get("users") or []:
            if not u.get("is_active"):
                continue
            created = u.get("created_at")
            if not created:
                continue
            try:
                created_dt = datetime.fromisoformat(created.replace("Z", "+00:00"))
            except Exception:
                continue
            days = (now - created_dt).days
            if days < 365:
                continue
            # Skip admins so we never lock the last operator out.
            if (u.get("role") or "").lower() == "admin":
                continue
            try:
                await _envirolytics_client.put(
                    f"/api/admin/users/{u['id']}/status",
                    params={"is_active": "false"},
                    headers={"Authorization": f"Bearer {token}"},
                )
                handled += 1
                logger.info(
                    "auto-deactivated %s (age=%dd)", u.get("email"), days,
                )
            except Exception as exc:
                logger.warning("auto-deactivate: PUT failed for %s: %s", u.get("id"), exc)
        # One admin's list is enough — every admin sees the same tenant.
        break
    logger.info("auto-deactivate cycle handled %d user(s)", handled)


@asynccontextmanager
async def lifespan(_: FastAPI):
    task = asyncio.create_task(_poller_loop())
    scheduler = AsyncIOScheduler(timezone=REPORT_TIMEZONE)
    # Weekly on Monday 06:00 IST, monthly on the 1st at 06:00 IST.
    scheduler.add_job(
        _send_scheduled_reports,
        CronTrigger(day_of_week="mon", hour=6, minute=0),
        args=["weekly"],
        id="weekly-reports",
        replace_existing=True,
    )
    scheduler.add_job(
        _send_scheduled_reports,
        CronTrigger(day=1, hour=6, minute=0),
        args=["monthly"],
        id="monthly-reports",
        replace_existing=True,
    )
    # Daily 03:00 IST auto-deactivate check for users past 365 days.
    scheduler.add_job(
        _auto_deactivate_expired_users,
        CronTrigger(hour=3, minute=0),
        id="auto-deactivate-expired",
        replace_existing=True,
    )
    scheduler.start()
    try:
        yield
    finally:
        scheduler.shutdown(wait=False)
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass
        await _push_client.aclose()
        await _envirolytics_client.aclose()
        _mongo.close()


app = FastAPI(lifespan=lifespan)
api_router = APIRouter(prefix="/api")


@api_router.get("/")
async def root():
    return {"status": "ok", "service": "envirolytics-mobile-backend"}


@api_router.get("/health")
async def health():
    return {"status": "ok", "poll_interval_s": ALERT_POLL_INTERVAL_SECONDS}


@api_router.post("/register-push", status_code=201)
async def register_push(body: RegisterPushBody):
    """Register the device token with the Emergent push service AND remember
    the user's Envirolytics token so the poller can check alerts on their
    behalf. Called on every app open — safe to call repeatedly.
    """
    upstream_payload = {
        "user_id": body.user_id,
        "platform": body.platform,
        "device_token": body.device_token,
    }
    resp = await _push_client.post(
        "/api/v1/push/users/register", json=upstream_payload
    )
    if resp.status_code == 401:
        raise HTTPException(500, "EMERGENT_PUSH_KEY missing or invalid")
    if resp.status_code >= 500:
        raise HTTPException(502, "Push provider unavailable")
    resp.raise_for_status()

    # Persist the user record so the poller can query alerts.
    update: dict[str, Any] = {
        "user_id": body.user_id,
        "platform": body.platform,
        "device_token": body.device_token,
        "token_invalid": False,
    }
    if body.envirolytics_token:
        update["envirolytics_token"] = body.envirolytics_token
    if body.email:
        update["email"] = body.email
    if body.full_name:
        update["full_name"] = body.full_name
    if body.role:
        update["role"] = body.role
    await db.push_users.update_one(
        {"user_id": body.user_id},
        {
            "$set": update,
            "$setOnInsert": {
                "known_offline": [],
                "known_breaches": [],
                "subscriptions": {"weekly": False, "monthly": False},
            },
        },
        upsert=True,
    )
    return {"status": "registered"}


class EmailReportBody(BaseModel):
    recipient: EmailStr
    envirolytics_token: str
    kinds: list[str] = Field(default_factory=lambda: ["flowmeter_csv", "flowmeter_pdf"])
    hardware_id: str | None = None
    days: int | None = None
    subject: str | None = None
    note: str | None = None


@api_router.post("/email-report")
async def email_report(body: EmailReportBody):
    subject = body.subject or "Envirolytics data export"
    intro = (
        f"<p>Hi,</p>"
        f"<p>{body.note or 'Here is the Envirolytics data export you requested from the mobile app.'}</p>"
    )
    await send_report_email(
        to_email=body.recipient,
        envirolytics_token=body.envirolytics_token,
        kinds=body.kinds,
        subject=subject,
        intro_html=intro,
        hardware_id=body.hardware_id,
        days=body.days,
    )
    return {"status": "sent", "recipient": body.recipient, "count": len(body.kinds)}


class SubscribeBody(BaseModel):
    user_id: str
    email: EmailStr
    envirolytics_token: str
    full_name: str | None = None
    weekly: bool = False
    monthly: bool = False


@api_router.post("/email-subscriptions")
async def set_email_subscription(body: SubscribeBody):
    await db.push_users.update_one(
        {"user_id": body.user_id},
        {
            "$set": {
                "user_id": body.user_id,
                "email": body.email,
                "envirolytics_token": body.envirolytics_token,
                "full_name": body.full_name,
                "subscriptions": {"weekly": body.weekly, "monthly": body.monthly},
            },
            "$setOnInsert": {"known_offline": [], "known_breaches": []},
        },
        upsert=True,
    )
    return {
        "status": "ok",
        "weekly": body.weekly,
        "monthly": body.monthly,
    }


@api_router.get("/email-subscriptions/{user_id}")
async def get_email_subscription(user_id: str):
    doc = await db.push_users.find_one(
        {"user_id": user_id}, {"_id": 0, "subscriptions": 1, "email": 1}
    )
    subs = (doc or {}).get("subscriptions") or {}
    return {
        "weekly": bool(subs.get("weekly")),
        "monthly": bool(subs.get("monthly")),
        "email": (doc or {}).get("email"),
    }


@api_router.post("/unregister-push")
async def unregister_push(body: dict):
    user_id = body.get("user_id")
    if not user_id:
        raise HTTPException(400, "user_id required")
    await db.push_users.delete_one({"user_id": user_id})
    return {"status": "unregistered"}


@api_router.post("/admin/run-auto-deactivate")
async def run_auto_deactivate_now():
    """Manual trigger for the daily auto-deactivate job. Returns immediately;
    logs cover the result."""
    asyncio.create_task(_auto_deactivate_expired_users())
    return {"status": "scheduled"}


app.include_router(api_router)
app.add_middleware(
    CORSMiddleware,
    allow_credentials=True,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
