name: Create Production Builds
jobs:
  build_android:
    type: build
    defaults:
      run:
        working_directory: ./frontend
    params:
      platform: android
      profile: production
  build_ios:
    type: build
    defaults:
      run:
        working_directory: ./frontend
    params:
      platform: ios
      profile: production
